Fix #106 #118: Show/Search and Delete branches and tags from dropdown
uvicgse/project-virtual-team-2 pull request #144
Opened 2019-06-21 04:26 UTC by AhmadAlsaif

Jamie implemented a feature on top of existing codebase to separate tags and branches. Made the search input field work and refactored both the design and code.

## Testing:
1. Navigate to the branches lists
2. observe that branches and tags are on two different lists
3. search for a branch and a tag
4. delete tags from the list

![59650007-6f6ba600-9139-11e9-90e7-e075441372a5](https://user-images.githubusercontent.com/39515277/59897517-d55a6680-93a1-11e9-9b3d-68cf0ca8332c.png)

2019-06-21 04:56 UTC, mdesco18 requested changes
Rebased old copy of master

2019-06-22 00:59 UTC, Leon0315 commented
I tested delete branch, the remote branch was deleted successfully 
<img width="462" alt="Screen Shot 2019-06-21 at 5 53 25 PM" src="https://user-images.githubusercontent.com/15313467/59957507-d1841e00-944d-11e9-915e-ce40e8524683.png">
However the branch is still shown in the drop down list and refresh won't help. When click on that branch it will check out to that branch but actually that branch doesn't exist anymore. 
<img width="565" alt="Screen Shot 2019-06-21 at 5 54 15 PM" src="https://user-images.githubusercontent.com/15313467/59957531-190aaa00-944e-11e9-8997-55d8477ce559.png">

2019-06-22 00:59 UTC, ajlarivi commented on app/misc/repo.ts
> +<<<<<<< HEAD
is this an unresolved merge conflict?

2019-06-22 01:01 UTC, cchampernowne commented
On linux, push/commit are working for issue106 (still buggy but that is preexisting). Pull is not detecting remote repo (likely not related to issues with this branch).
Tagging functionality appears to be working.

2019-06-22 01:04 UTC, ajlarivi requested changes
**tested the following functionality successfully on MacOS**
- Navigate to the branches lists
- observe that branches and tags are on two different lists
- search for a branch and a tag
- delete tags from the list

additionally, as much functionality of the rest of the application was tested without finding any issues. commit, push, adding tags, fetch, etc. all performed as expected. 

The only issue found was an unresolved merge conflict in the code? Not really sure what the deal is there. See individual comment on the modified files.

2019-06-23 00:25 UTC, AhmadAlsaif commented on app/misc/repo.ts
> +<<<<<<< HEAD
Resolved

2019-06-23 00:40 UTC, AhmadAlsaif commented
@Leon0315, delete branch was not listed in the issues we were working on. However, there's another issue for it https://github.com/uvicgse/project-virtual-team-2/issues/129

2019-06-23 02:25 UTC, ajlarivi submitted a review, later dismissed
merge conflict resolved. Approving.

2019-06-23 02:49 UTC, AhmadAlsaif commented
> On linux, push/commit are working for issue106 (still buggy but that is preexisting). Pull is not detecting remote repo (likely not related to issues with this branch).
> Tagging functionality appears to be working.

If it's working well on your machine, can you approve it please?

2019-06-23 16:13 UTC, merged