WIP: Issue #89 push branch to origin
uvicgse/project-virtual-team-2 pull request #97
Opened 2019-06-10 03:41 UTC by cchampernowne

Created modal triggered by pushing to remote branch that doesnt exist. 
TODO:
-formatting
-connect correct function to "run command" button. Currently, it logs the user out

test case:
push to remote branch that doesn't exist

2019-06-11 18:11 UTC, cchampernowne commented
on my windows 10 machine, createUpstreamPush() isnt actually creating a remote repo. 
Visual git believes it is creating one but every time the app is restart, it seems to think the repo is only local again. 

Note: I have hardcoded values for issue 101 which could be causing interactions other users wont have

2019-06-12 18:25 UTC, aujlarj commented
I tried testing the branch but it shows the Warning message even when there is nothing to commit or push. :-(

2019-06-13 06:31 UTC, katland commented
I went to test this for a review and I can't log in on this branch. I enter my username and password and it just hangs on the "Signing in". I see no reason why the changes you've made would affect sign in so I'm assuming something went wrong on my end and will look into it. Just posting this on the off chance someone else goes to review this and has the same issue.

2019-06-14 02:29 UTC, katland requested changes
When testing I am able to get the warning error when trying to push to a repository I have only committed in and do not have a remote for. If I select the 'back' option it closes the window and continues running properly. This part is good. However if I select the 'run command' option, the application sends me back to the log in screen. (I assume the 'run command' button should be running the command without logging the user out?) From here I can repeat the same steps to get the same result:
1 - log in
2 - open the repository with only a local commit
3 - select push
4 - select run command
5 - be sent back to the log in screen to begin again
![Screen Shot 2019-06-13 at 7 18 54 PM](https://user-images.githubusercontent.com/10343127/59479074-7a0ffd80-8e10-11e9-9a32-cf0961336a7c.png)


EDIT:
These issues were resolved by updating my version of the branch with help from @smithmr 
step1 `git check master`
step2 `git pull`
step3 `git branch -D {branch name}` only do this if you have not committed anything to this branch
step4 `git checkout {branch name}`

**Does the code work? Did I test it locally? What OS am I using? Does it perform its intended function, the logic is correct etc.**
Yes, makes the test branch visible on github in my testing repository. Mac OS 10.13
**Is the code well documented? Would it be easily understood to other developers?**
yes
**Does it have correct linting/formatting?**
yes
**Is there any redundant or duplicate code? Any hard-coded values?**
no
**Can any of the code be replaced with library functions?**
no
**Are good names used for methods, variables, etc.? Do they follow naming conventions?**
yes
**Were any other issues found?**
no

2019-06-14 05:19 UTC, katland approved these changes

2019-06-14 05:54 UTC, mdesco18 commented on app/misc/git.ts
> +  let branch = document.getElementById("branch-name").innerText;
Update this before merge

2019-06-14 06:18 UTC, mdesco18 requested changes
**Does the code work? Did I test it locally? What OS am I using? Does it perform its intended function, the logic is correct etc.** Windows 10. It works well on a repository that has a origin/remotes already existing and sets the upstreams correctly for a push when there is not one. 
**Is the code well documented? Would it be easily understood to other developers?**
very well documented
**Does it have correct linting/formatting?**
follows the formatting of similar git functions  well
**Is there any redundant or duplicate code? Any hard-coded values?** no
**Can any of the code be replaced with library functions?** no
**Are good names used for methods, variables, etc.? Do they follow naming conventions?** yes
**Were any other issues found?** aside from certain error checks, no.

2019-06-14 06:18 UTC, mdesco18 commented on app/misc/git.ts
> +  let remoteBranch = "refs/heads/";
this should be refs/remotes/origin/ or the checkIfExistsOrigin() isnt working

The function still continues even on my local repository with no remotes

Suggested edit: have an error thrown if no remote repositories exist

2019-06-14 06:18 UTC, mdesco18 commented on app/misc/git.ts
> +  let branch = document.getElementById("branch-name").innerText;
update this before merge

2019-06-14 06:18 UTC, mdesco18 commented on app/misc/git.ts
> +  let branch = document.getElementById("branch-name").innerText;
update to new function

2019-06-14 17:16 UTC, cchampernowne commented on app/misc/git.ts
> +  let branch = document.getElementById("branch-name").innerText;
what did you want updated here?

2019-06-14 19:04 UTC, smithmr commented on app/misc/git.ts
> +  let branch = document.getElementById("branch-name").innerText;
@cchampernowne He wants the getBranch() function

2019-06-18 04:15 UTC, katland commented
Have followed up on testing the new changes and they work on my machine.

2019-06-19 01:06 UTC, mdesco18 commented on app/misc/git.ts
> +  let remoteBranch = "refs/heads/";
Suggestion Implemented

2019-06-19 01:06 UTC, mdesco18 commented on app/misc/git.ts
> +  let branch = document.getElementById("branch-name").innerText;
Suggestion Implemented

2019-06-19 01:06 UTC, mdesco18 commented on app/misc/git.ts
> +  let branch = document.getElementById("branch-name").innerText;
Suggestion Implemented

2019-06-19 01:08 UTC, mdesco18 approved these changes
**Does the code work? Did I test it locally? What OS am I using? Does it perform its intended function, the logic is correct etc.** Yes, Windows 10 tested
**Is the code well documented? Would it be easily understood to other developers?** yes
**Does it have correct linting/formatting?** yes
**Is there any redundant or duplicate code? Any hard-coded values?** no
**Can any of the code be replaced with library functions?** No, uses user functions
**Are good names used for methods, variables, etc.? Do they follow naming conventions?** Yes
**Were any other issues found?** Issues were resolved

2019-06-19 01:34 UTC, Leon0315 approved these changes
**Does the code work? Did I test it locally? What OS am I using? Does it perform its intended function, the logic is correct etc.** 

Tested on Mac OS 10.14 works well when I followed the test instruction. The branch created locally has successfully been pushed to remote, and the warning message is also clear.

**Is the code well documented? Would it be easily understood to other developers?**
Yes, the logic is clear and easy to follow

**Does it have correct linting/formatting?**
yes

**Is there any redundant or duplicate code? Any hard-coded values?** 
no

**Can any of the code be replaced with library functions?** 
no

**Are good names used for methods, variables, etc.? Do they follow naming conventions?** 
yes

**Were any other issues found? aside from certain error checks.**
 no.

2019-06-19 02:30 UTC, merged